#1 Feat/edit menu
nattsnb/Menu-App pull request #1
Opened 2024-08-02 16:53 UTC by nattsnb

PR with first page of the app

2024-08-05 10:04 UTC, Solnick requested changes

2024-08-05 10:04 UTC, Solnick commented on menu/EditableMenuEntry.js
> +  createDishNameP() {
```suggestion
  createDishNameParagraph() {
```
Let's use the full names, so it is clear.

2024-08-05 10:04 UTC, Solnick commented on menu/EditableMenuEntry.js
> +  createPriceWithCurrencyDiv() {
Here the name is ok

2024-08-19 15:41 UTC, Solnick requested changes
![Screenshot 2024-08-19 at 17 40 32](https://github.com/user-attachments/assets/1d5de4e1-00b0-4188-a487-2248113d8ffc)
The text is still displayed wrong.

2024-08-19 15:51 UTC, Solnick requested changes

2024-08-19 15:51 UTC, Solnick commented on README.txt
> +Basic website file structure, nothing to display.
The file extension should be `.md`

2024-08-19 15:51 UTC, Solnick commented on RestaurantMenu.js
> +  displayEditableMenu() {
please keep the consistency. If you are using arrow functions for class methods, use it for every class method

2024-08-19 15:51 UTC, Solnick commented on menu/EditableMenuEntry.js
> +    const editResponse = await fetch(
Please create a new class `ProductsAPI` which will take care of all the  product's requests in the app. For example
```
class ProductsAPI {
  baseUrl = 'http://localhost:3000/products';
  .....
  patchProduct(editedProduct) {
    return fetch(
     `${this.baseUrl}/${this.dishAndPriceArray[this.i].id}`,
      {
        method: "PATCH",
        body: JSON.stringify(editedProduct),
        headers: {
          "Content-Type": "application/json",
        },
      },
    );
  }
}
```

Same goes for the Orders api

2024-08-20 06:10 UTC, nattsnb commented on README.txt
> +Basic website file structure, nothing to display.
done

2024-08-20 06:14 UTC, nattsnb commented on RestaurantMenu.js
> +  displayEditableMenu() {
done

2024-08-21 10:50 UTC, nattsnb commented on menu/EditableMenuEntry.js
> +    const editResponse = await fetch(
done

2024-08-21 15:43 UTC, Solnick requested changes

2024-08-21 15:43 UTC, Solnick commented on ProductsAPI.js
> +    return fetch(`http://localhost:3000/products/${id}`, {
why in `getProducts` you are using the `this.serverAddress` but in the rest of the methods you are not?

2024-08-21 15:43 UTC, Solnick commented on menu/NewEntryForm.js
> +    const newEntryData = await postResponse.json();
this should be a part of the API class method

2024-08-21 15:43 UTC, Solnick commented on menu/NewEntryForm.js
> +    }
I've see those lines in multiple places, please don't repeat yourself

2024-08-21 16:43 UTC, nattsnb commented on ProductsAPI.js
> +    return fetch(`http://localhost:3000/products/${id}`, {
done

2024-08-21 17:00 UTC, nattsnb commented on menu/NewEntryForm.js
> +    const newEntryData = await postResponse.json();
I did that for function getProducts, but in quoted function Im using both the response as well as json later in code so I think it could stay? Or should I divide it into two functions in API class?

2024-08-21 17:02 UTC, nattsnb commented on menu/NewEntryForm.js
> +    }
my current version of code, has these lines put to handleResponse function as you suggested earlier. i dont understand why you are seeing them.

2024-08-21 17:41 UTC, Solnick requested changes

2024-08-21 17:41 UTC, Solnick commented on ProductsAPI.js
> +    return await getResponse.json();
`return await promise` has no point. You are already returning a promise because the method is async, so the await is not changing anything. It would make sense only if you would use try catch in the method, but you don't need try catch here.

https://stackoverflow.com/questions/38708550/difference-between-return-await-promise-and-return-promise

2024-08-21 17:41 UTC, Solnick commented on menu/NewEntryForm.js
> +    const newEntryData = await postResponse.json();
so return an object from the API method:
```
{ 
 data: <the resolved json data>,
 response,
 }
 ```

2024-08-22 11:47 UTC, nattsnb commented on menu/NewEntryForm.js
> +    const newEntryData = await postResponse.json();
done

2024-08-22 11:47 UTC, nattsnb commented on ProductsAPI.js
> +    return await getResponse.json();
done

2024-08-22 14:46 UTC, Solnick approved these changes

2024-08-22 14:46 UTC, Solnick commented on ProductsAPI.js
> +    return { data: data, responseStatus: patchResponse.status };
Please use the property shorthand syntax (first lesson about objects)

2024-08-26 12:34 UTC, merged