#2 Order menu
nattsnb/Menu-App pull request #2
Opened 2024-08-18 19:12 UTC by nattsnb

#2

/localhost:XXXX/ 

Website where customer can edit and place the order. Plus/minus buttons allows to add number of dishes to order. Form asks to provide the address. If both provided it does create new order on the server and pops out confirmation to move to order status tracking page.

2024-08-19 15:55 UTC, Solnick requested changes
![Screenshot 2024-08-19 at 17 54 17](https://github.com/user-attachments/assets/4bf5f8e8-be8a-4757-8e88-f6604767053e)
When no address is provided, there should be no order created. Please validate if the form is filled out before sending the request

2024-08-19 15:59 UTC, Solnick requested changes

2024-08-19 15:59 UTC, Solnick commented on OrderMenuEntry.js
> +        let obj = this.orderData.products.find(
`obj` is not a very descriptive name

2024-08-19 15:59 UTC, Solnick commented on ProvideAddressAndOrderForm.js
> +      this.errorMessage.innerText = `Order placed. Order number ${this.orderNumber}`;
those lines of code are in multiple places. Please figure out how you can not repeat yourself. Maybe there should be a `handleResponse` function in the API class…

2024-08-21 11:56 UTC, nattsnb commented on OrderMenuEntry.js
> +        let obj = this.orderData.products.find(
done

2024-08-21 12:44 UTC, nattsnb commented on ProvideAddressAndOrderForm.js
> +      this.errorMessage.innerText = `Order placed. Order number ${this.orderNumber}`;
done

2024-08-21 15:44 UTC, Solnick requested changes

2024-08-21 15:44 UTC, Solnick commented on OrdersAPI.js
> +      errorMessageP.innerText = "Error, provide data.";
do not mutate function arguments it is an anti-pattern

2024-08-22 16:14 UTC, nattsnb commented on OrdersAPI.js
> +      errorMessageP.innerText = "Error, provide data.";
done

2024-08-26 12:13 UTC, Solnick requested changes

2024-08-26 12:13 UTC, Solnick commented on OrderMenuEntry.js
> +      this.orderData.products.push(productOrder);
```
      this.orderData.products.push(productOrder);
```
This code is executed no matter if the condition is met or not. There is no point in keeping it duplicated in first and second case. Put it outside of the if else. Then you will see that only one condition is reqiuered.

2024-08-26 12:13 UTC, Solnick commented on OrdersAPI.js
> +      errorMessageP.innerText = "Error, provide data.";
I can still see the mutation of the properties values. Just return a new object.

2024-08-26 16:00 UTC, Solnick requested changes

2024-08-26 16:00 UTC, Solnick commented on menu/EditableMenuEntry.js
> +    } else
please add curly brackets to the else statement

2024-08-27 07:52 UTC, nattsnb commented on OrderMenuEntry.js
> +      this.orderData.products.push(productOrder);
done

2024-08-27 07:55 UTC, nattsnb commented on menu/EditableMenuEntry.js
> +    } else
done

2024-08-27 15:40 UTC, Solnick requested changes

2024-08-27 15:40 UTC, Solnick commented on OrderMenuEntry.js
> +      if (this.numberOfPlates !== 0) {
ohh, so much better <3

2024-08-27 15:40 UTC, Solnick commented on OrdersAPI.js
> +      return "Error, provide data.";
Good!

2024-08-27 15:40 UTC, Solnick commented on ProductsAPI.js
> +  handleResponse(response) {
I think this can be put in base class so OrdersApi and ProductsApi can inherit from it, because the logic is the same - the one from OrdersAPI is better because of 500 error handling

2024-08-27 15:40 UTC, Solnick commented on ProvideAddressAndOrderForm.js
> +          this.townPostCodeInput.value) !== ""
What exactly you want to check here?

Because this code will:
1. check if `this.streetInput.value` is truthy
2. if 1. is true it will check if `this.townInput.value` truthy
3. if 2. is true it will check if `this.townPostCodeInput.value` is not equal to empty string

2024-08-27 15:54 UTC, Solnick requested changes

2024-08-27 15:54 UTC, Solnick commented on OrderMenuEntry.js
> +        (x) => x.id === this.dishAndPriceArray[this.i].id,
Please don't use one letter arguments or variables names. I've already pointed it out

2024-08-27 15:54 UTC, Solnick commented on OrderMenuEntry.js
> +        (x) => x.id === this.dishAndPriceArray[this.i].id,
Also if you are not going to change the value of dish, you must use the `const` instead of `let`

2024-08-28 08:58 UTC, nattsnb commented on ProductsAPI.js
> +  handleResponse(response) {
done

2024-08-28 08:59 UTC, nattsnb commented on ProvideAddressAndOrderForm.js
> +          this.townPostCodeInput.value) !== ""
done

2024-08-28 09:02 UTC, nattsnb commented on OrderMenuEntry.js
> +        (x) => x.id === this.dishAndPriceArray[this.i].id,
done

2024-08-28 09:04 UTC, merged

2024-08-28 11:47 UTC, mwanago commented on API.js
> +    } else if (response === 404) {
This `else` statement is not necessary

2024-08-28 11:49 UTC, mwanago commented on OrderMenuEntry.js
> +      let productOrder = {
Always declare variables using `const` if possible

2024-08-28 11:51 UTC, mwanago commented on RestaurantMenu.js
> +    for (let i = 0; i < this.dishAndPriceArray.length; i++) {
You could use `forEeach` to simplify this a little

2024-08-28 11:53 UTC, mwanago commented on style.css
> +#logo-container {
I would avoid using ids when styling to prevent issues related to specificity of the selectors

2024-08-28 11:54 UTC, mwanago commented on style.css
> +  border-style: solid;
You can group various border-related properties into a single `border` property
https://developer.mozilla.org/en-US/docs/Web/CSS/border

2024-08-29 08:26 UTC, nattsnb commented on API.js
> +    } else if (response === 404) {
done

2024-08-29 08:27 UTC, nattsnb commented on OrderMenuEntry.js
> +      let productOrder = {
done

2024-08-29 08:36 UTC, nattsnb commented on RestaurantMenu.js
> +    for (let i = 0; i < this.dishAndPriceArray.length; i++) {
probably, but the EditableMenuEntries, these are created with this loop, they need to know their order in the data array to display data in the right manner. Changing the loop now would need massive changes in the code...

2024-08-29 08:39 UTC, nattsnb commented on style.css
> +  border-style: solid;
done