#3 Feat/orders
nattsnb/Menu-App pull request #4
Opened 2024-08-28 10:46 UTC by nattsnb

Third branch of this repo. It displays owners view to manage orders.

2024-08-28 11:57 UTC, mwanago commented on orders/OrderEntry.js
> +      this.ordersDataAraay[this.orderEntryNumber].status === "Delivery"
This is quite difficult to read. Introduce additional variables.
```
const status = this.ordersDataAraay[this.orderEntryNumber].status;
```

2024-08-28 11:58 UTC, mwanago commented on orders/OrderEntry.js
> +
This empty newline here is a bit inconsistent. You're not doing that between other methods in this class. Either do it between all methods or don't do it - be consistent.

2024-08-28 12:00 UTC, mwanago commented on status/UserStatusWindow.js
> +  displayStatusWindow() {
This method is quite difficult to read - too many things happen here. Either introduce newlines to group parts of the code or create smaller methods.

2024-08-28 18:21 UTC, Solnick requested changes

2024-08-28 18:21 UTC, Solnick commented on orders/OrdersStatusList.js
> +    this.productsAPI = new ProductsAPI(this.serverAddress);
the OrdersAPI and ProductsAPI is a singleton. So you can create the instance once and export it so all of the files are using the exact same instance.

2024-08-28 18:21 UTC, Solnick commented on orders/OrdersStatusList.js
> +      .reverse();
calling `reverse` cost you `O(n)` complexity. Please find out how can you change the sorting order by changing only the comparator function.

2024-08-28 18:21 UTC, Solnick commented on status/UserStatusWindow.js
> +  refreshStatusOrder = async () => {};
do you need this?

2024-08-28 18:21 UTC, Solnick commented on orders/OrderEntry.js
> +    this.ordersDataAraay = ordersDataArray;
typo here

2024-08-28 18:26 UTC, Solnick requested changes

2024-08-28 18:26 UTC, Solnick commented on orders/OrdersStatusList.js
> +      .reverse();
Please don't use one letter variables/arguments, I have pointed it out multiple times already

2024-08-28 18:26 UTC, Solnick commented on orders/OrderEntry.js
> +    const orderID = document.createElement("div");
You are using both `createOrderIdDiv` and `orderID` notation. You need to be consistent with the code style. If you are using `orderId` notation then use it everywhere, if you are using `orderID` also use it everywhere.

I propose to go with `orderId`, rather than `orderID`

2024-08-29 08:46 UTC, nattsnb commented on orders/OrderEntry.js
> +      this.ordersDataAraay[this.orderEntryNumber].status === "Delivery"
done

2024-08-29 08:46 UTC, nattsnb commented on orders/OrderEntry.js
> +
done

2024-08-29 08:51 UTC, nattsnb commented on status/UserStatusWindow.js
> +  displayStatusWindow() {
next branch changes

2024-08-29 09:56 UTC, nattsnb commented on orders/OrdersStatusList.js
> +      .reverse();
done

2024-08-29 09:56 UTC, nattsnb commented on status/UserStatusWindow.js
> +  refreshStatusOrder = async () => {};
next branch changes

2024-08-29 09:57 UTC, nattsnb commented on orders/OrderEntry.js
> +    this.ordersDataAraay = ordersDataArray;
done

2024-08-29 09:59 UTC, nattsnb commented on orders/OrderEntry.js
> +    const orderID = document.createElement("div");
done

2024-08-31 13:08 UTC, Solnick approved these changes

2024-08-31 13:18 UTC, merged